[build]
  command = "npm install && npm run build"
  functions = "functions"
[context.production]
  command = "npm run start"
[context.branch-deploy]
  command = "npm run start"
[context.deploy-preview]
  command = "npm run start"
[context.env]
  NODE_ENV = "production"